<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Rithesh" failures="1" tests="2" name="Test(failed)" time="25.38" errors="0" timestamp="2025-07-13T10:09:36 IST">
  <testcase classname="differentapp.LaunchApplication" name="testTwo" time="11.504">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase classname="differentapp.LaunchApplication" name="testTwo" time="8.308">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at differentapp.TextBoxApp.testBox(TextBoxApp.java:22)
at differentapp.LaunchApplication.testTwo(LaunchApplication.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testTwo -->
  <testcase classname="differentapp.LaunchApplication" name="test" time="0.0">
    <ignored/>
  </testcase> <!-- test -->
</testsuite> <!-- Test(failed) -->
